FROM ubuntu:latest

# The ENTRYPOINT instruction sets the main command to be executed when the container starts
ENTRYPOINT ["echo", "Hello"]

# The CMD instruction provides default arguments for the ENTRYPOINT command, which can be overridden when running the container
CMD ["World!"]